### ISSUE TITLE
Converting qs file to qs2 files - add info to README

### ISSUE THREAD

**Issue by benjaminhlina** [qsbase/qs2#32]
Yes `.qs` to `.qs2` files are not compatible but one can use [rig](https://rig.r-lib.org/) to install older version of R (e.g., 4.3), then use `pak::pak_install("qs")` to install `{qs}`. Then read in the files using `qs::qread()`, convert to `*.rds`. At this point, you could leave files as `*.rds` or convert the `*.rds` to a `*.qs2`. I just did this and it was very simple and efficent workaround that might be worth detailing out for people that are stuck in this situation.

**Comment by erzakiev** [comment]
You could probably just install the last version of qs from the [CRAN archive](https://cran.r-project.org/src/contrib/Archive/qs/) via its tar gzip source archive without installing a different version of R...

**Comment by benjaminhlina** [comment]
I've tried this and it doesn't work at least on R v4.6.1 on iOS as it causes a build error to occur.

**Comment by benjaminhlina** [comment]
See below which is how I found the [rig](https://rig.r-lib.org/) work around for this. 

``` r
> sessioninfo::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.6.1 (2026-06-24)
 os       macOS Tahoe 26.6.2
 system   aarch64, darwin23
 ui       Positron
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Toronto
 date     2026-09-24
 pandoc   3.8 @ /opt/homebrew/anaconda3/bin/pandoc
 quarto   1.10.18 @ /Applications/Positron.app/Contents/Resources/app/quarto/bin/quarto

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cli           3.6.6   2026-04-09 [1] CRAN (R 4.6.0)
 sessioninfo   1.2.4   2026-06-04 [2] CRAN (R 4.6.0)

 [1] /Users/benhlina/Library/R/arm64/4.6/library
 [2] /Library/Frameworks/R.framework/Versions/4.6/Resources/library

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> install.packages(
+   '/Users/benhlina/Downloads/qs_0.27.3.tar.gz',
+   repos = NULL,
+   type = "source"
+ )
Installing package into ‘/Users/benhlina/Library/R/arm64/4.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘qs’ ...
** this is package ‘qs’ version ‘0.27.3’
** package ‘qs’ successfully unpacked and MD5 sums checked
** using staged installation
checking for pkg-config... /opt/homebrew/bin/pkg-config
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ -arch arm64 -std=gnu++20 accepts -g... yes
C++ compiler: clang++ -arch arm64 -std=gnu++20
Does not require -latomic flag
zstd 1.5.7 library detected -- skipping zstd compilation
lz4 1.10.0 library detected -- skipping lz4 compilation
configure: creating ./config.status
config.status: creating src/Makevars
** libs
using C++ compiler: ‘Apple clang version 21.0.0 (clang-2100.1.1.101)’
using SDK: ‘MacOSX26.5.sdk’
clang++ -arch arm64 -std=gnu++20 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I. -I/opt/homebrew/opt/zstd/include -I/opt/homebrew/opt/lz4/include  -I'/Users/benhlina/Library/R/arm64/4.6/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.6/Resources/library/RApiSerialize/include' -I'/Users/benhlina/Library/R/arm64/4.6/library/stringfish/include' -I'/Library/Frameworks/R.framework/Versions/4.6/Resources/library/BH/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2   -c RcppExports.cpp -o RcppExports.o
clang++ -arch arm64 -std=gnu++20 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I. -I/opt/homebrew/opt/zstd/include -I/opt/homebrew/opt/lz4/include  -I'/Users/benhlina/Library/R/arm64/4.6/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.6/Resources/library/RApiSerialize/include' -I'/Users/benhlina/Library/R/arm64/4.6/library/stringfish/include' -I'/Library/Frameworks/R.framework/Versions/4.6/Resources/library/BH/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2   -c qs_functions.cpp -o qs_functions.o
In file included from qs_functions.cpp:21:
In file included from ./qs_common.h:87:
In file included from /Users/benhlina/Library/R/arm64/4.6/library/stringfish/include/sf_external.h:6:
In file included from /Users/benhlina/Library/R/arm64/4.6/library/stringfish/include/sf_internal.h:5:
In file included from /Users/benhlina/Library/R/arm64/4.6/library/stringfish/include/sf_internal/string_types.h:5:
/Users/benhlina/Library/R/arm64/4.6/library/stringfish/include/sf_internal/../simple_array/small_array.h:17:22: warning: 'is_pod<char>' is deprecated [-Wdeprecated-declarations]
   17 |   static_assert(std::is_pod<T>::value, "small_array type should be POD");
      |                      ^
/Users/benhlina/Library/R/arm64/4.6/library/stringfish/include/sf_internal/string_types.h:20:15: note: in instantiation of template class 'trqwe::small_array<char, std::allocator<char>, unsigned long, std::integral_constant<unsigned long, 8>>' requested here
   20 | static_assert(sizeof(sfstring_storage) == sizeof(std::string),
      |               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_pod.h:22:8: note: 'is_pod<char>' has been explicitly marked deprecated here
   22 | struct _LIBCPP_DEPRECATED_IN_CXX20 _LIBCPP_NO_SPECIALIZATIONS is_pod : integral_constant<bool, __is_pod(_Tp)> {};
      |        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:587:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX20'
  587 | #    define _LIBCPP_DEPRECATED_IN_CXX20 _LIBCPP_DEPRECATED
      |                                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:554:49: note: expanded from macro '_LIBCPP_DEPRECATED'
  554 | #      define _LIBCPP_DEPRECATED __attribute__((__deprecated__))
      |                                                 ^
In file included from qs_functions.cpp:21:
./qs_common.h:1210:15: error: use of undeclared identifier 'LEVELS'
 1210 |   int flags = LEVELS(obj);
      |               ^~~~~~
./qs_common.h:1211:7: error: use of undeclared identifier 'OBJECT'
 1211 |   if (OBJECT(obj)) flags |= IS_OBJECT_BIT_MASK;
      |       ^~~~~~
./qs_common.h:1218:3: error: use of undeclared identifier 'SETLEVELS'
 1218 |   SETLEVELS(obj, levs);
      |   ^~~~~~~~~
./qs_common.h:1219:3: error: use of undeclared identifier 'SET_OBJECT'
 1219 |   SET_OBJECT(obj, isobj);
      |   ^~~~~~~~~~
In file included from qs_functions.cpp:23:
In file included from ./qs_serialization.h:22:
./qs_serialize_common.h:295:16: error: use of undeclared identifier 'ATTRIB'
  295 |   SEXP alist = ATTRIB(x);
      |                ^~~~~~
./qs_serialize_common.h:315:13: error: use of undeclared identifier 'FRAME'
  315 |   SEXP xt = FRAME(rho);
      |             ^~~~~
./qs_serialize_common.h:335:24: error: use of undeclared identifier 'Rf_findVarInFrame'
  335 |         cars.push_back(Rf_findVarInFrame(rho, tag));
      |                        ^~~~~~~~~~~~~~~~~
./qs_serialize_common.h:384:17: error: use of undeclared identifier 'ATTRIB'
  384 |     SEXP info = ATTRIB(ALTREP_CLASS(x));
      |                 ^~~~~~
./qs_serialize_common.h:400:46: error: no member named 'c_str' in 'trqwe::small_array<char, std::allocator<char>, unsigned long, std::integral_constant<unsigned long, 8>>'
  400 |           sobj->push_contiguous(ref[i].sdata.c_str(), ref[i].sdata.size());
      |                                 ~~~~~~~~~~~~ ^
./qs_serialize_common.h:404:46: error: no member named 'c_str' in 'trqwe::small_array<char, std::allocator<char>, unsigned long, std::integral_constant<unsigned long, 8>>'
  404 |           sobj->push_contiguous(ref[i].sdata.c_str(), ref[i].sdata.size());
      |                                 ~~~~~~~~~~~~ ^
./qs_serialize_common.h:422:6: error: use of undeclared identifier 'IS_S4_OBJECT'
  422 |   if(IS_S4_OBJECT(x)) writeS4Flag_common(sobj);
      |      ^~~~~~~~~~~~
./qs_serialize_common.h:531:8: error: use of undeclared identifier 'LEVELS'
  531 |     if(LEVELS(x) != 0 || OBJECT(x) != 0) {
      |        ^~~~~~
./qs_serialize_common.h:531:26: error: use of undeclared identifier 'OBJECT'
  531 |     if(LEVELS(x) != 0 || OBJECT(x) != 0) {
      |                          ^~~~~~
./qs_serialize_common.h:592:27: error: use of undeclared identifier 'ENCLOS'
  592 |         writeObject(sobj, ENCLOS(x)); // parent env
      |                           ^~~~~~
./qs_serialize_common.h:595:27: error: use of undeclared identifier 'HASHTAB'
  595 |         writeObject(sobj, HASHTAB(x));
      |                           ^~~~~~~
In file included from qs_functions.cpp:25:
In file included from ./qs_deserialization.h:22:
./qs_deserialize_common.h:387:19: error: use of undeclared identifier 'Rf_allocSExp'
  387 |     PROTECT(obj = Rf_allocSExp(LANGSXP)); pt++;
      |                   ^~~~~~~~~~~~
./qs_deserialize_common.h:390:19: error: use of undeclared identifier 'Rf_allocSExp'
  390 |     PROTECT(obj = Rf_allocSExp(CLOSXP)); pt++;
      |                   ^~~~~~~~~~~~
./qs_deserialize_common.h:393:19: error: use of undeclared identifier 'Rf_allocSExp'
  393 |     PROTECT(obj = Rf_allocSExp(PROMSXP)); pt++;
      |                   ^~~~~~~~~~~~
./qs_deserialize_common.h:396:19: error: use of undeclared identifier 'Rf_allocSExp'
  396 |     PROTECT(obj = Rf_allocSExp(DOTSXP)); pt++;
      |                   ^~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [qs_functions.o] Error 1
ERROR: compilation failed for package ‘qs’
* removing ‘/Users/benhlina/Library/R/arm64/4.6/library/qs’
Warning message:
In install.packages("/Users/benhlina/Downloads/qs_0.27.3.tar.gz",  :
  installation of package ‘/Users/benhlina/Downloads/qs_0.27.3.tar.gz’ had non-zero exit status
```

**Comment by traversc** [comment]
@benjaminhlina that's a good idea, but I'd make a separate Rmarkdown vignette file, and then link to it from the readme. Would you be interested in writing a PR?

One simplification: you can install both qs and qs2 on R 4.3, so it's not necessary to save to an intermediate RDS.

@erzakiev R 4.6 API has changed, so qs isn't compatible. It probably works on R 4.5, but 4.3 is definitely safe.

**Comment by benjaminhlina** [comment]
@traversc I'll try to whip something up here shortly and agree that a vignette is the right choice of how to proceed. Definitely can make a simplification in not making them `.rds` files. I think based on `.qs` issues my head went to needing to make `.rds` files first as an intermediate. 

I have tried on R v4.5 and it will not work 4.4 and 4.3 it does
